#!/usr/bin/env python3
"""
Script to load and analyze neural spike data generated by the Rust neuro-sim
"""

import sys
import os
current_dir = os.path.dirname(os.path.abspath(__file__))
src_dir = os.path.join(current_dir, '../src')
sys.path.append(src_dir)

from memorymapping.processor import NeuroDataProcessor

def main():
    # Check if the Rust output file exists
    # Check if the data file exists
    rust_output_file = "data/sample_neuro_data.json"
    
    if not os.path.exists(rust_output_file):
        print(f"Error: {rust_output_file} not found!")
        print("Please run the Rust simulator first:")
        print("cd neuro-sim-rust && cargo run")
        return
    
    print("Loading neural spike data from Rust simulator...")
    
    # Create processor and load actual Rust data
    processor = NeuroDataProcessor()
    
    if processor.load_rust_spike_data(rust_output_file):
        print("Successfully loaded Rust neural simulation data!")
        
        # Analyze the real neural patterns
        analysis_file = processor.analyze_spike_patterns()
        
        print(f"\nAnalysis complete!")
        print(f"Results saved to: {analysis_file}")
        
        # Print some statistics
        print(f"\nData Summary:")
        print(f"- Total spike events: {len(processor.spike_events)}")
        print(f"- Environmental contexts: {len(processor.environmental_context)}")
        
        # Show spike type distribution
        spike_types = {}
        for spike in processor.spike_events:
            spike_type = spike.spike_type.value
            spike_types[spike_type] = spike_types.get(spike_type, 0) + 1
        
        print(f"\nSpike Type Distribution:")
        for spike_type, count in sorted(spike_types.items()):
            percentage = (count / len(processor.spike_events)) * 100
            print(f"- {spike_type}: {count} ({percentage:.1f}%)")
        
        # Show brain region activity (by analyzing neuron positions)
        print(f"\nSpatial Distribution:")
        x_coords = [s.position[0] for s in processor.spike_events]
        y_coords = [s.position[1] for s in processor.spike_events]
        z_coords = [s.position[2] for s in processor.spike_events]
        
        print(f"- X range: {min(x_coords):.1f} to {max(x_coords):.1f} mm")
        print(f"- Y range: {min(y_coords):.1f} to {max(y_coords):.1f} mm") 
        print(f"- Z range: {min(z_coords):.1f} to {max(z_coords):.1f} mm")
        
    else:
        print("Failed to load Rust neural data!")

if __name__ == "__main__":
    main() 